# Generated by Django 3.0.5 on 2020-05-26 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_content', '0001_squashed_0006_auto_20200509_0845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='static_page',
            name='content',
        ),
        migrations.RemoveField(
            model_name='static_page',
            name='header',
        ),
        migrations.RemoveField(
            model_name='static_page',
            name='onmenu',
        ),
        migrations.RemoveField(
            model_name='static_page',
            name='order',
        ),
        migrations.RemoveField(
            model_name='static_page',
            name='title',
        ),
        migrations.RemoveField(
            model_name='static_page',
            name='updated_date',
        ),
        migrations.AddField(
            model_name='static_page',
            name='css',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='static_page',
            name='html',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='static_page',
            name='scripts',
            field=models.TextField(default=''),
        ),
    ]
